[versions]
# App Version
app-versioncode = "1"
app-versionname = "0.3.0"
# SDK Version
sdk-min = "24"
sdk-target = "34"
sdk-compile = "34"
# Plugin Version
plugin-gradle = "8.5.1"
plugin-gms = "4.4.2"
plugin-firebase-crashlytics = "3.0.2"
# Kotlin
kotlin = "2.0.0"
ksp = "2.0.0-1.0.24"
coroutines = "1.8.1"
kotlinx-datetime = "0.5.0"
# Hilt
hilt = "2.51.1"
hilt-compose = "1.2.0"
# AndroidX
androidx-core = "1.13.1"
androidx-appcompat = "1.7.0"
androidx-room = "2.6.1"
androidx-paging = "3.3.1"
androidx-datastore = "1.1.1"
androidx-compose = "1.6.8"
androidx-compose-navigation = "2.7.7"
androidx-compose-lifecycle = "2.8.4"
androidx-compose-material3 = "1.2.1"
androidx-compose-constraintlayout = "1.0.1"
androidx-test = "1.6.1"
androidx-test-ext-junit = "1.2.1"
androidx-test-ext-truth = "1.6.0"
androidx-credentials="1.3.0"
# Network
ktor = "2.3.11"
kotlinx-serialization = "1.6.3"
krossbow = "8.0.0"
# UI
coil-compose = "2.6.0"
lottie = "6.4.0"
holix-bottomsheet = "1.4.1"
googleid = "1.1.1"
# Kakao
kakao = "2.20.1"
# Logging
timber = "5.0.1"
firebase-bom = "33.1.2"
# Debug
leakcanary = "2.14"
okhttp3-logging-interceptor = "4.12.0"
# Common
ted-permission = "3.3.0"
# Test
junit4 = "4.13.2"
robolectric = "4.13"

[libraries]
# Kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-compose" }
# AndroidX Presentation
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-compose-navigation" }
androidx-compose-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-compose-lifecycle" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-compose-constraintlayout" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
androidx-credentials-play-services = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidx-credentials" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidx-credentials" }
# AndroidX Data
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-coroutine = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }
androidx-paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
# Network
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor-websocket = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-kotlinx-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
krossbow-stomp-core = { module = "org.hildan.krossbow:krossbow-stomp-core", version.ref = "krossbow" }
krossbow-websocket-ktor = { module = "org.hildan.krossbow:krossbow-websocket-ktor", version.ref = "krossbow" }
# UI
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
ted-permission = { module = "io.github.ParkSangGwon:tedpermission-coroutine", version.ref = "ted-permission" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
holix-bottomsheet = { module = "com.holix.android:bottomsheetdialog-compose", version.ref = "holix-bottomsheet" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
# Kakao
kakao-user = { module = "com.kakao.sdk:v2-user", version.ref = "kakao" }
# Logging
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
# Debug
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3-logging-interceptor" }
# Test
junit4 = { module = "junit:junit", version = "junit4" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-ext-truth = { module = "androidx.test.ext:truth", version.ref = "androidx-test-ext-truth" }
robolectric-robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-gradle" }
android-library = { id = "com.android.library", version.ref = "plugin-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
gms = { id = "com.google.gms.google-services", version.ref = "plugin-gms" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "plugin-firebase-crashlytics" }

[bundles]
kotlin = ["kotlin", "kotlinx-coroutines-android", "kotlinx-coroutines-core", "kotlinx-datetime"]
androidx-presentation = ["androidx-core", "androidx-appcompat", "androidx-compose-ui",
    "androidx-compose-material3", "androidx-compose-navigation", "androidx-compose-constraintlayout",
    "androidx-compose-lifecycle", "holix-bottomsheet", "androidx-paging-compose",
    "androidx-credentials", "androidx-credentials-play-services", "googleid"]
androidx-data = ["androidx-room-runtime", "androidx-room-coroutine", "androidx-paging-runtime",
    "androidx-datastore-preferences"]
network = ["ktor-core", "ktor-okhttp", "ktor-resources", "ktor-websocket",
    "ktor-content-negotiation", "ktor-kotlinx-serialization", "ktor-auth", "kotlinx-serialization",
    "krossbow-stomp-core", "krossbow-websocket-ktor"]
kakao = ["kakao-user"]
logging = ["timber", "firebase-analytics", "firebase-crashlytics", "firebase-messaging"]
test = ["junit4", "kotlinx-coroutines-test", "hilt-android-testing", "androidx-test-core",
    "androidx-test-runner", "androidx-test-rules", "androidx-test-ext-junit",
    "androidx-test-ext-truth", "robolectric-robolectric"]
