package kr.linkerbell.boardlink.android.presentation.ui.main.home

object SettingConstant {
    const val ROUTE = "setting"

    // 하위 스크린을 위한 변수들 - 이름은 협의 통해 수정
    const val ROUTE_ARGUMENT_SCREEN_MAIN = "main"
    const val ROUTE_ARGUMENT_SCREEN_PROFILE = "profile"
    const val ROUTE_ARGUMENT_SCREEN_INQUIRY = "inquiry"
    const val ROUTE_ARGUMENT_SCREEN_AGREEMENT = "agreement"
    const val ROUTE_ARGUMENT_SCREEN_NOTIFICATION = "notification"

    // 이 부분은 어떻게 처리할지? -> 논의 사항, 특히 "탈퇴" 부분
    const val ROUTE_ARGUMENT_SCREEN_LOGOUT = "logout"
    const val ROUTE_ARGUMENT_SCREEN_WITHDRAWAL = "withdrawal"

    const val ROUTE_STRUCTURE_MAIN = "$ROUTE?$ROUTE_ARGUMENT_SCREEN_MAIN={$ROUTE_ARGUMENT_SCREEN_MAIN}"
    const val ROUTE_STRUCTURE_PROFILE = "$ROUTE?$ROUTE_ARGUMENT_SCREEN_PROFILE={$ROUTE_ARGUMENT_SCREEN_PROFILE}"
    const val ROUTE_STRUCTURE_INQUIRY = "$ROUTE?$ROUTE_ARGUMENT_SCREEN_INQUIRY={$ROUTE_ARGUMENT_SCREEN_INQUIRY}"
    const val ROUTE_STRUCTURE_AGREEMENT = "$ROUTE?$ROUTE_ARGUMENT_SCREEN_AGREEMENT={$ROUTE_ARGUMENT_SCREEN_AGREEMENT}"
    const val ROUTE_STRUCTURE_NOTIFICATION = "$ROUTE?$ROUTE_ARGUMENT_SCREEN_NOTIFICATION={$ROUTE_ARGUMENT_SCREEN_NOTIFICATION}"

    const val ROUTE_STRUCTURE_LOGOUT = "$ROUTE?$ROUTE_ARGUMENT_SCREEN_LOGOUT={$ROUTE_ARGUMENT_SCREEN_LOGOUT}"
    const val ROUTE_STRUCTURE_WITHDRAWAL = "$ROUTE?$ROUTE_ARGUMENT_SCREEN_WITHDRAWAL={$ROUTE_ARGUMENT_SCREEN_WITHDRAWAL}"
}
